name: Python package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@master
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}